// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.stripe-subscription-admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const STRIPE_SUBSCRIPTION_ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const STRIPE_SUBSCRIPTION_ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_stripe_subscription_admin { () => { "{\"capability_id\":\"lenso.stripe-subscription-admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"ingest_webhook\",\"inspect_effect\",\"reconcile_next\",\"resolve_unknown_effect\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_stripe_subscription_admin_client { () => { "{\"capability_id\":\"lenso.stripe-subscription-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_stripe_subscription_admin_client { () => { "{\"capability_id\":\"lenso.stripe-subscription-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const INGEST_WEBHOOK_OPERATION: &str = "ingest_webhook";
pub const INSPECT_EFFECT_OPERATION: &str = "inspect_effect";
pub const RECONCILE_NEXT_OPERATION: &str = "reconcile_next";
pub const RESOLVE_UNKNOWN_EFFECT_OPERATION: &str = "resolve_unknown_effect";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IngestWebhookRequest {
    #[serde(rename = "raw_body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub raw_body: String,
    #[serde(rename = "signature_header")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub signature_header: String,
}

impl fmt::Debug for IngestWebhookRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("IngestWebhookRequest")
            .field("raw_body", &"<redacted>")
            .field("signature_header", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IngestWebhookResponse {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_type: String,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: IngestWebhookResponseOutcome,
    #[serde(rename = "reconciliation_enqueued")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reconciliation_enqueued: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum IngestWebhookResponseOutcome {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "ignored")]
    Ignored,
}

#[derive(Clone, Debug, PartialEq)]
pub enum IngestWebhookError {
    BodyTooLarge,
    Forbidden,
    InvalidEvent,
    InvalidSignature,
    StaleSignature,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectEffectRequest {
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectEffectResponse {
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Option<Timestamp>,
    #[serde(rename = "failure_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_code: Option<String>,
    #[serde(rename = "operation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation: InspectEffectResponseOperation,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: InspectEffectResponseStatus,
    #[serde(rename = "stripe_object_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub stripe_object_id: Option<String>,
    #[serde(rename = "url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub url: Option<String>,
}

impl fmt::Debug for InspectEffectResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("InspectEffectResponse")
            .field("effect_id", &self.effect_id)
            .field("expires_at", &self.expires_at)
            .field("failure_code", &self.failure_code)
            .field("operation", &self.operation)
            .field("status", &self.status)
            .field("stripe_object_id", &self.stripe_object_id)
            .field("url", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InspectEffectResponseOperation {
    #[serde(rename = "checkout")]
    Checkout,
    #[serde(rename = "portal")]
    Portal,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InspectEffectResponseStatus {
    #[serde(rename = "prepared")]
    Prepared,
    #[serde(rename = "in_flight")]
    InFlight,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "known_failure")]
    KnownFailure,
    #[serde(rename = "effect_unknown")]
    EffectUnknown,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InspectEffectError {
    Forbidden,
    InvalidEffect,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReconcileNextRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReconcileNextResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Option<i64>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ReconcileNextResponseStatus,
    #[serde(rename = "subscription_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subscription_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReconcileNextResponseStatus {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "converged")]
    Converged,
    #[serde(rename = "retry_pending")]
    RetryPending,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReconcileNextError {
    Forbidden,
    InvalidState,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveUnknownEffectRequest {
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Option<Timestamp>,
    #[serde(rename = "failure_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_code: Option<String>,
    #[serde(rename = "resolution")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resolution: ResolveUnknownEffectRequestResolution,
    #[serde(rename = "stripe_object_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub stripe_object_id: Option<String>,
    #[serde(rename = "url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub url: Option<String>,
}

impl fmt::Debug for ResolveUnknownEffectRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ResolveUnknownEffectRequest")
            .field("effect_id", &self.effect_id)
            .field("expires_at", &self.expires_at)
            .field("failure_code", &self.failure_code)
            .field("resolution", &self.resolution)
            .field("stripe_object_id", &self.stripe_object_id)
            .field("url", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ResolveUnknownEffectRequestResolution {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "known_failure")]
    KnownFailure,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveUnknownEffectResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ResolveUnknownEffectResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ResolveUnknownEffectResponseStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "known_failure")]
    KnownFailure,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResolveUnknownEffectError {
    Forbidden,
    InvalidResolution,
    NotFound,
    NotUnknown,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct StripeSubscriptionAdminIngestWebhook;
impl RequestCapability for StripeSubscriptionAdminIngestWebhook {
    type Request = IngestWebhookRequest;
    type Response = IngestWebhookResponse;
    type DomainError = IngestWebhookError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INGEST_WEBHOOK_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).ingest_webhook(context, request)
    }
}

#[derive(Debug)]
pub struct StripeSubscriptionAdminInspectEffect;
impl RequestCapability for StripeSubscriptionAdminInspectEffect {
    type Request = InspectEffectRequest;
    type Response = InspectEffectResponse;
    type DomainError = InspectEffectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INSPECT_EFFECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).inspect_effect(context, request)
    }
}

#[derive(Debug)]
pub struct StripeSubscriptionAdminReconcileNext;
impl RequestCapability for StripeSubscriptionAdminReconcileNext {
    type Request = ReconcileNextRequest;
    type Response = ReconcileNextResponse;
    type DomainError = ReconcileNextError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RECONCILE_NEXT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).reconcile_next(context, request)
    }
}

#[derive(Debug)]
pub struct StripeSubscriptionAdminResolveUnknownEffect;
impl RequestCapability for StripeSubscriptionAdminResolveUnknownEffect {
    type Request = ResolveUnknownEffectRequest;
    type Response = ResolveUnknownEffectResponse;
    type DomainError = ResolveUnknownEffectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESOLVE_UNKNOWN_EFFECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).resolve_unknown_effect(context, request)
    }
}

impl serde::Serialize for IngestWebhookError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::BodyTooLarge => serializer.serialize_str("body_too_large"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::InvalidSignature => serializer.serialize_str("invalid_signature"),
            Self::StaleSignature => serializer.serialize_str("stale_signature"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for IngestWebhookError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "body_too_large" => Ok(Self::BodyTooLarge),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_event" => Ok(Self::InvalidEvent),
                "invalid_signature" => Ok(Self::InvalidSignature),
                "stale_signature" => Ok(Self::StaleSignature),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InspectEffectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidEffect => serializer.serialize_str("invalid_effect"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InspectEffectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_effect" => Ok(Self::InvalidEffect),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReconcileNextError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidState => serializer.serialize_str("invalid_state"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReconcileNextError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_state" => Ok(Self::InvalidState),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ResolveUnknownEffectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidResolution => serializer.serialize_str("invalid_resolution"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::NotUnknown => serializer.serialize_str("not_unknown"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ResolveUnknownEffectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_resolution" => Ok(Self::InvalidResolution),
                "not_found" => Ok(Self::NotFound),
                "not_unknown" => Ok(Self::NotUnknown),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_ingest_webhook_request(value: &IngestWebhookRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ingest_webhook_request(wire: &str) -> Result<IngestWebhookRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ingest_webhook_response(value: &IngestWebhookResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ingest_webhook_response(wire: &str) -> Result<IngestWebhookResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ingest_webhook_error(value: &IngestWebhookError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ingest_webhook_error(wire: &str) -> Result<IngestWebhookError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_inspect_effect_request(value: &InspectEffectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_effect_request(wire: &str) -> Result<InspectEffectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_effect_response(value: &InspectEffectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_effect_response(wire: &str) -> Result<InspectEffectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_effect_error(value: &InspectEffectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_effect_error(wire: &str) -> Result<InspectEffectError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_reconcile_next_request(value: &ReconcileNextRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reconcile_next_request(wire: &str) -> Result<ReconcileNextRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_reconcile_next_response(value: &ReconcileNextResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reconcile_next_response(wire: &str) -> Result<ReconcileNextResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_reconcile_next_error(value: &ReconcileNextError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reconcile_next_error(wire: &str) -> Result<ReconcileNextError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_resolve_unknown_effect_request(value: &ResolveUnknownEffectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_unknown_effect_request(wire: &str) -> Result<ResolveUnknownEffectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_unknown_effect_response(value: &ResolveUnknownEffectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_unknown_effect_response(wire: &str) -> Result<ResolveUnknownEffectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_unknown_effect_error(value: &ResolveUnknownEffectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_unknown_effect_error(wire: &str) -> Result<ResolveUnknownEffectError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionAdminIngestWebhookResult {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionAdminIngestWebhookResult for Result<IngestWebhookResponse, IngestWebhookError> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionAdminIngestWebhookResult for Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionAdminIngestWebhookResult for Result<IngestWebhookResponse, lenso_plugin_authoring::PluginError<IngestWebhookError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionAdminIngestWebhookResult for Result<IngestWebhookResponse, StripeSubscriptionAdminIngestWebhookInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<IngestWebhookResponse, IngestWebhookError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionAdminIngestWebhookInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionAdminIngestWebhookInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionAdminInspectEffectResult {
    fn __lenso_into_result(self) -> Result<Result<InspectEffectResponse, InspectEffectError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionAdminInspectEffectResult for Result<InspectEffectResponse, InspectEffectError> {
    fn __lenso_into_result(self) -> Result<Result<InspectEffectResponse, InspectEffectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionAdminInspectEffectResult for Result<Result<InspectEffectResponse, InspectEffectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InspectEffectResponse, InspectEffectError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionAdminInspectEffectResult for Result<InspectEffectResponse, lenso_plugin_authoring::PluginError<InspectEffectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InspectEffectResponse, InspectEffectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionAdminInspectEffectResult for Result<InspectEffectResponse, StripeSubscriptionAdminInspectEffectInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InspectEffectResponse, InspectEffectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionAdminInspectEffectInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionAdminInspectEffectInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionAdminReconcileNextResult {
    fn __lenso_into_result(self) -> Result<Result<ReconcileNextResponse, ReconcileNextError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionAdminReconcileNextResult for Result<ReconcileNextResponse, ReconcileNextError> {
    fn __lenso_into_result(self) -> Result<Result<ReconcileNextResponse, ReconcileNextError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionAdminReconcileNextResult for Result<Result<ReconcileNextResponse, ReconcileNextError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReconcileNextResponse, ReconcileNextError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionAdminReconcileNextResult for Result<ReconcileNextResponse, lenso_plugin_authoring::PluginError<ReconcileNextError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReconcileNextResponse, ReconcileNextError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionAdminReconcileNextResult for Result<ReconcileNextResponse, StripeSubscriptionAdminReconcileNextInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReconcileNextResponse, ReconcileNextError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionAdminReconcileNextInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionAdminReconcileNextInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionAdminResolveUnknownEffectResult {
    fn __lenso_into_result(self) -> Result<Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionAdminResolveUnknownEffectResult for Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionAdminResolveUnknownEffectResult for Result<Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionAdminResolveUnknownEffectResult for Result<ResolveUnknownEffectResponse, lenso_plugin_authoring::PluginError<ResolveUnknownEffectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionAdminResolveUnknownEffectResult for Result<ResolveUnknownEffectResponse, StripeSubscriptionAdminResolveUnknownEffectInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveUnknownEffectResponse, ResolveUnknownEffectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionAdminResolveUnknownEffectInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionAdminResolveUnknownEffectInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait StripeSubscriptionAdminProvider: fmt::Debug + 'static {
    fn ingest_webhook(&self, context: InvocationContext, request: IngestWebhookRequest) -> NativeRequestFuture<StripeSubscriptionAdminIngestWebhook>;
    fn inspect_effect(&self, context: InvocationContext, request: InspectEffectRequest) -> NativeRequestFuture<StripeSubscriptionAdminInspectEffect>;
    fn reconcile_next(&self, context: InvocationContext, request: ReconcileNextRequest) -> NativeRequestFuture<StripeSubscriptionAdminReconcileNext>;
    fn resolve_unknown_effect(&self, context: InvocationContext, request: ResolveUnknownEffectRequest) -> NativeRequestFuture<StripeSubscriptionAdminResolveUnknownEffect>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_stripe_subscription_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportStripeSubscriptionAdmin;
        impl $crate::StripeSubscriptionAdminProvider for $plugin {
        fn ingest_webhook(&self, context: __LensoNativeSupportStripeSubscriptionAdmin::InvocationContext, request: $crate::IngestWebhookRequest) -> __LensoNativeSupportStripeSubscriptionAdmin::NativeRequestFuture<$crate::StripeSubscriptionAdminIngestWebhook> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::ingest_webhook(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionAdminIngestWebhookResult::__lenso_into_result(result)
            })
        }
        fn inspect_effect(&self, context: __LensoNativeSupportStripeSubscriptionAdmin::InvocationContext, request: $crate::InspectEffectRequest) -> __LensoNativeSupportStripeSubscriptionAdmin::NativeRequestFuture<$crate::StripeSubscriptionAdminInspectEffect> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::inspect_effect(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionAdminInspectEffectResult::__lenso_into_result(result)
            })
        }
        fn reconcile_next(&self, context: __LensoNativeSupportStripeSubscriptionAdmin::InvocationContext, request: $crate::ReconcileNextRequest) -> __LensoNativeSupportStripeSubscriptionAdmin::NativeRequestFuture<$crate::StripeSubscriptionAdminReconcileNext> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::reconcile_next(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionAdminReconcileNextResult::__lenso_into_result(result)
            })
        }
        fn resolve_unknown_effect(&self, context: __LensoNativeSupportStripeSubscriptionAdmin::InvocationContext, request: $crate::ResolveUnknownEffectRequest) -> __LensoNativeSupportStripeSubscriptionAdmin::NativeRequestFuture<$crate::StripeSubscriptionAdminResolveUnknownEffect> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::resolve_unknown_effect(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionAdminResolveUnknownEffectResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct StripeSubscriptionAdminRequestEndpoint { provider: Rc<dyn StripeSubscriptionAdminProvider> }

#[derive(Debug)]
pub struct StripeSubscriptionAdminEndpoint<P: StripeSubscriptionAdminProvider> { provider: Rc<P>, request_endpoint: StripeSubscriptionAdminRequestEndpoint }
impl<P: StripeSubscriptionAdminProvider> StripeSubscriptionAdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn StripeSubscriptionAdminProvider> = provider.clone();
        Self { provider, request_endpoint: StripeSubscriptionAdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: StripeSubscriptionAdminProvider> NativeRequestEndpoint for StripeSubscriptionAdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        INGEST_WEBHOOK_OPERATION,
        INSPECT_EFFECT_OPERATION,
        RECONCILE_NEXT_OPERATION,
        RESOLVE_UNKNOWN_EFFECT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            INGEST_WEBHOOK_OPERATION => {
                let Ok(request) = request.downcast::<IngestWebhookRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).ingest_webhook(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INSPECT_EFFECT_OPERATION => {
                let Ok(request) = request.downcast::<InspectEffectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).inspect_effect(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RECONCILE_NEXT_OPERATION => {
                let Ok(request) = request.downcast::<ReconcileNextRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).reconcile_next(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RESOLVE_UNKNOWN_EFFECT_OPERATION => {
                let Ok(request) = request.downcast::<ResolveUnknownEffectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).resolve_unknown_effect(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_stripe_subscription_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::StripeSubscriptionAdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_stripe_subscription_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_stripe_subscription_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct StripeSubscriptionAdminClient {
    ingest_webhook: NativeRequestHandle<StripeSubscriptionAdminIngestWebhook>,
    inspect_effect: NativeRequestHandle<StripeSubscriptionAdminInspectEffect>,
    reconcile_next: NativeRequestHandle<StripeSubscriptionAdminReconcileNext>,
    resolve_unknown_effect: NativeRequestHandle<StripeSubscriptionAdminResolveUnknownEffect>,
}
impl StripeSubscriptionAdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn ingest_webhook(&self, request: IngestWebhookRequest) -> Result<IngestWebhookResponse, StripeSubscriptionAdminIngestWebhookInvocationError> {
        self.ingest_webhook.invoke(INGEST_WEBHOOK_OPERATION, request).await
            .map_err(StripeSubscriptionAdminIngestWebhookInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminIngestWebhookInvocationError::Domain)
    }

    pub async fn ingest_webhook_with_context(&self, context: InvocationContext, request: IngestWebhookRequest) -> Result<IngestWebhookResponse, StripeSubscriptionAdminIngestWebhookInvocationError> {
        self.ingest_webhook.invoke_with_context(INGEST_WEBHOOK_OPERATION, context, request).await
            .map_err(StripeSubscriptionAdminIngestWebhookInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminIngestWebhookInvocationError::Domain)
    }

    pub async fn inspect_effect(&self, request: InspectEffectRequest) -> Result<InspectEffectResponse, StripeSubscriptionAdminInspectEffectInvocationError> {
        self.inspect_effect.invoke(INSPECT_EFFECT_OPERATION, request).await
            .map_err(StripeSubscriptionAdminInspectEffectInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminInspectEffectInvocationError::Domain)
    }

    pub async fn inspect_effect_with_context(&self, context: InvocationContext, request: InspectEffectRequest) -> Result<InspectEffectResponse, StripeSubscriptionAdminInspectEffectInvocationError> {
        self.inspect_effect.invoke_with_context(INSPECT_EFFECT_OPERATION, context, request).await
            .map_err(StripeSubscriptionAdminInspectEffectInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminInspectEffectInvocationError::Domain)
    }

    pub async fn reconcile_next(&self, request: ReconcileNextRequest) -> Result<ReconcileNextResponse, StripeSubscriptionAdminReconcileNextInvocationError> {
        self.reconcile_next.invoke(RECONCILE_NEXT_OPERATION, request).await
            .map_err(StripeSubscriptionAdminReconcileNextInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminReconcileNextInvocationError::Domain)
    }

    pub async fn reconcile_next_with_context(&self, context: InvocationContext, request: ReconcileNextRequest) -> Result<ReconcileNextResponse, StripeSubscriptionAdminReconcileNextInvocationError> {
        self.reconcile_next.invoke_with_context(RECONCILE_NEXT_OPERATION, context, request).await
            .map_err(StripeSubscriptionAdminReconcileNextInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminReconcileNextInvocationError::Domain)
    }

    pub async fn resolve_unknown_effect(&self, request: ResolveUnknownEffectRequest) -> Result<ResolveUnknownEffectResponse, StripeSubscriptionAdminResolveUnknownEffectInvocationError> {
        self.resolve_unknown_effect.invoke(RESOLVE_UNKNOWN_EFFECT_OPERATION, request).await
            .map_err(StripeSubscriptionAdminResolveUnknownEffectInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminResolveUnknownEffectInvocationError::Domain)
    }

    pub async fn resolve_unknown_effect_with_context(&self, context: InvocationContext, request: ResolveUnknownEffectRequest) -> Result<ResolveUnknownEffectResponse, StripeSubscriptionAdminResolveUnknownEffectInvocationError> {
        self.resolve_unknown_effect.invoke_with_context(RESOLVE_UNKNOWN_EFFECT_OPERATION, context, request).await
            .map_err(StripeSubscriptionAdminResolveUnknownEffectInvocationError::Runtime)?
            .map_err(StripeSubscriptionAdminResolveUnknownEffectInvocationError::Domain)
    }
}

impl CapabilityClient for StripeSubscriptionAdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            ingest_webhook: dependencies.one::<StripeSubscriptionAdminIngestWebhook>()?,
            inspect_effect: dependencies.one::<StripeSubscriptionAdminInspectEffect>()?,
            reconcile_next: dependencies.one::<StripeSubscriptionAdminReconcileNext>()?,
            resolve_unknown_effect: dependencies.one::<StripeSubscriptionAdminResolveUnknownEffect>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for StripeSubscriptionAdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    ingest_webhook: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionAdminIngestWebhook>()?,
                    inspect_effect: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionAdminInspectEffect>()?,
                    reconcile_next: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionAdminReconcileNext>()?,
                    resolve_unknown_effect: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionAdminResolveUnknownEffect>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionAdminIngestWebhookInvocationError {
    Domain(IngestWebhookError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionAdminInspectEffectInvocationError {
    Domain(InspectEffectError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionAdminReconcileNextInvocationError {
    Domain(ReconcileNextError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionAdminResolveUnknownEffectInvocationError {
    Domain(ResolveUnknownEffectError),
    Runtime(RuntimeFailure),
}
