// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.stripe-subscription@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const STRIPE_SUBSCRIPTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const STRIPE_SUBSCRIPTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_stripe_subscription { () => { "{\"capability_id\":\"lenso.stripe-subscription@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"create_checkout_session\",\"create_portal_session\",\"get_subscription\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_stripe_subscription_client { () => { "{\"capability_id\":\"lenso.stripe-subscription@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_stripe_subscription_client { () => { "{\"capability_id\":\"lenso.stripe-subscription@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CREATE_CHECKOUT_SESSION_OPERATION: &str = "create_checkout_session";
pub const CREATE_PORTAL_SESSION_OPERATION: &str = "create_portal_session";
pub const GET_SUBSCRIPTION_OPERATION: &str = "get_subscription";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateCheckoutSessionRequest {
    #[serde(rename = "cancel_url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cancel_url: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "price_alias")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub price_alias: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "success_url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub success_url: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateCheckoutSessionResponse {
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Option<Timestamp>,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: Option<String>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CreateCheckoutSessionResponseStatus,
    #[serde(rename = "url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub url: Option<String>,
}

impl fmt::Debug for CreateCheckoutSessionResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateCheckoutSessionResponse")
            .field("effect_id", &self.effect_id)
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("status", &self.status)
            .field("url", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateCheckoutSessionResponseStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "effect_unknown")]
    EffectUnknown,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateCheckoutSessionError {
    AlreadySubscribed,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    PriceNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreatePortalSessionRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "return_url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub return_url: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreatePortalSessionResponse {
    #[serde(rename = "effect_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Option<Timestamp>,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: Option<String>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CreatePortalSessionResponseStatus,
    #[serde(rename = "url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub url: Option<String>,
}

impl fmt::Debug for CreatePortalSessionResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreatePortalSessionResponse")
            .field("effect_id", &self.effect_id)
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("status", &self.status)
            .field("url", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreatePortalSessionResponseStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "effect_unknown")]
    EffectUnknown,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreatePortalSessionError {
    CustomerNotFound,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetSubscriptionRequest {
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetSubscriptionResponse {
    #[serde(rename = "cancel_at_period_end")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cancel_at_period_end: bool,
    #[serde(rename = "current_period_end")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub current_period_end: Option<Timestamp>,
    #[serde(rename = "customer_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub customer_id: String,
    #[serde(rename = "entitlement_state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entitlement_state: GetSubscriptionResponseEntitlementState,
    #[serde(rename = "price_alias")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub price_alias: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: i64,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: GetSubscriptionResponseStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "subscription_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subscription_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetSubscriptionResponseEntitlementState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "granted")]
    Granted,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetSubscriptionResponseStatus {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "incomplete")]
    Incomplete,
    #[serde(rename = "incomplete_expired")]
    IncompleteExpired,
    #[serde(rename = "trialing")]
    Trialing,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "past_due")]
    PastDue,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "unpaid")]
    Unpaid,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetSubscriptionError {
    Forbidden,
    InvalidRequest,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct StripeSubscriptionCreateCheckoutSession;
impl RequestCapability for StripeSubscriptionCreateCheckoutSession {
    type Request = CreateCheckoutSessionRequest;
    type Response = CreateCheckoutSessionResponse;
    type DomainError = CreateCheckoutSessionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_CHECKOUT_SESSION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_checkout_session(context, request)
    }
}

#[derive(Debug)]
pub struct StripeSubscriptionCreatePortalSession;
impl RequestCapability for StripeSubscriptionCreatePortalSession {
    type Request = CreatePortalSessionRequest;
    type Response = CreatePortalSessionResponse;
    type DomainError = CreatePortalSessionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_PORTAL_SESSION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_portal_session(context, request)
    }
}

#[derive(Debug)]
pub struct StripeSubscriptionGetSubscription;
impl RequestCapability for StripeSubscriptionGetSubscription {
    type Request = GetSubscriptionRequest;
    type Response = GetSubscriptionResponse;
    type DomainError = GetSubscriptionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_SUBSCRIPTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<StripeSubscriptionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_subscription(context, request)
    }
}

impl serde::Serialize for CreateCheckoutSessionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadySubscribed => serializer.serialize_str("already_subscribed"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::PriceNotFound => serializer.serialize_str("price_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateCheckoutSessionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_subscribed" => Ok(Self::AlreadySubscribed),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "price_not_found" => Ok(Self::PriceNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CreatePortalSessionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CustomerNotFound => serializer.serialize_str("customer_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreatePortalSessionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "customer_not_found" => Ok(Self::CustomerNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetSubscriptionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetSubscriptionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_create_checkout_session_request(value: &CreateCheckoutSessionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_checkout_session_request(wire: &str) -> Result<CreateCheckoutSessionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_checkout_session_response(value: &CreateCheckoutSessionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_checkout_session_response(wire: &str) -> Result<CreateCheckoutSessionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_checkout_session_error(value: &CreateCheckoutSessionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_checkout_session_error(wire: &str) -> Result<CreateCheckoutSessionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_create_portal_session_request(value: &CreatePortalSessionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_portal_session_request(wire: &str) -> Result<CreatePortalSessionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_portal_session_response(value: &CreatePortalSessionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_portal_session_response(wire: &str) -> Result<CreatePortalSessionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_portal_session_error(value: &CreatePortalSessionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_portal_session_error(wire: &str) -> Result<CreatePortalSessionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_subscription_request(value: &GetSubscriptionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_subscription_request(wire: &str) -> Result<GetSubscriptionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_subscription_response(value: &GetSubscriptionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_subscription_response(wire: &str) -> Result<GetSubscriptionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_subscription_error(value: &GetSubscriptionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_subscription_error(wire: &str) -> Result<GetSubscriptionError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionCreateCheckoutSessionResult {
    fn __lenso_into_result(self) -> Result<Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionCreateCheckoutSessionResult for Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError> {
    fn __lenso_into_result(self) -> Result<Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionCreateCheckoutSessionResult for Result<Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionCreateCheckoutSessionResult for Result<CreateCheckoutSessionResponse, lenso_plugin_authoring::PluginError<CreateCheckoutSessionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionCreateCheckoutSessionResult for Result<CreateCheckoutSessionResponse, StripeSubscriptionCreateCheckoutSessionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateCheckoutSessionResponse, CreateCheckoutSessionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionCreateCheckoutSessionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionCreateCheckoutSessionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionCreatePortalSessionResult {
    fn __lenso_into_result(self) -> Result<Result<CreatePortalSessionResponse, CreatePortalSessionError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionCreatePortalSessionResult for Result<CreatePortalSessionResponse, CreatePortalSessionError> {
    fn __lenso_into_result(self) -> Result<Result<CreatePortalSessionResponse, CreatePortalSessionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionCreatePortalSessionResult for Result<Result<CreatePortalSessionResponse, CreatePortalSessionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreatePortalSessionResponse, CreatePortalSessionError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionCreatePortalSessionResult for Result<CreatePortalSessionResponse, lenso_plugin_authoring::PluginError<CreatePortalSessionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreatePortalSessionResponse, CreatePortalSessionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionCreatePortalSessionResult for Result<CreatePortalSessionResponse, StripeSubscriptionCreatePortalSessionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreatePortalSessionResponse, CreatePortalSessionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionCreatePortalSessionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionCreatePortalSessionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoStripeSubscriptionGetSubscriptionResult {
    fn __lenso_into_result(self) -> Result<Result<GetSubscriptionResponse, GetSubscriptionError>, RuntimeFailure>;
}
impl __LensoIntoStripeSubscriptionGetSubscriptionResult for Result<GetSubscriptionResponse, GetSubscriptionError> {
    fn __lenso_into_result(self) -> Result<Result<GetSubscriptionResponse, GetSubscriptionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoStripeSubscriptionGetSubscriptionResult for Result<Result<GetSubscriptionResponse, GetSubscriptionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetSubscriptionResponse, GetSubscriptionError>, RuntimeFailure> { self }
}
impl __LensoIntoStripeSubscriptionGetSubscriptionResult for Result<GetSubscriptionResponse, lenso_plugin_authoring::PluginError<GetSubscriptionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetSubscriptionResponse, GetSubscriptionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoStripeSubscriptionGetSubscriptionResult for Result<GetSubscriptionResponse, StripeSubscriptionGetSubscriptionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetSubscriptionResponse, GetSubscriptionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(StripeSubscriptionGetSubscriptionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(StripeSubscriptionGetSubscriptionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait StripeSubscriptionProvider: fmt::Debug + 'static {
    fn create_checkout_session(&self, context: InvocationContext, request: CreateCheckoutSessionRequest) -> NativeRequestFuture<StripeSubscriptionCreateCheckoutSession>;
    fn create_portal_session(&self, context: InvocationContext, request: CreatePortalSessionRequest) -> NativeRequestFuture<StripeSubscriptionCreatePortalSession>;
    fn get_subscription(&self, context: InvocationContext, request: GetSubscriptionRequest) -> NativeRequestFuture<StripeSubscriptionGetSubscription>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_stripe_subscription {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportStripeSubscription;
        impl $crate::StripeSubscriptionProvider for $plugin {
        fn create_checkout_session(&self, context: __LensoNativeSupportStripeSubscription::InvocationContext, request: $crate::CreateCheckoutSessionRequest) -> __LensoNativeSupportStripeSubscription::NativeRequestFuture<$crate::StripeSubscriptionCreateCheckoutSession> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_checkout_session(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionCreateCheckoutSessionResult::__lenso_into_result(result)
            })
        }
        fn create_portal_session(&self, context: __LensoNativeSupportStripeSubscription::InvocationContext, request: $crate::CreatePortalSessionRequest) -> __LensoNativeSupportStripeSubscription::NativeRequestFuture<$crate::StripeSubscriptionCreatePortalSession> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_portal_session(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionCreatePortalSessionResult::__lenso_into_result(result)
            })
        }
        fn get_subscription(&self, context: __LensoNativeSupportStripeSubscription::InvocationContext, request: $crate::GetSubscriptionRequest) -> __LensoNativeSupportStripeSubscription::NativeRequestFuture<$crate::StripeSubscriptionGetSubscription> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_subscription(&plugin, context, request).await;
                $crate::__LensoIntoStripeSubscriptionGetSubscriptionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct StripeSubscriptionRequestEndpoint { provider: Rc<dyn StripeSubscriptionProvider> }

#[derive(Debug)]
pub struct StripeSubscriptionEndpoint<P: StripeSubscriptionProvider> { provider: Rc<P>, request_endpoint: StripeSubscriptionRequestEndpoint }
impl<P: StripeSubscriptionProvider> StripeSubscriptionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn StripeSubscriptionProvider> = provider.clone();
        Self { provider, request_endpoint: StripeSubscriptionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: StripeSubscriptionProvider> NativeRequestEndpoint for StripeSubscriptionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CREATE_CHECKOUT_SESSION_OPERATION,
        CREATE_PORTAL_SESSION_OPERATION,
        GET_SUBSCRIPTION_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CREATE_CHECKOUT_SESSION_OPERATION => {
                let Ok(request) = request.downcast::<CreateCheckoutSessionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_checkout_session(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CREATE_PORTAL_SESSION_OPERATION => {
                let Ok(request) = request.downcast::<CreatePortalSessionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_portal_session(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_SUBSCRIPTION_OPERATION => {
                let Ok(request) = request.downcast::<GetSubscriptionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_subscription(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_stripe_subscription {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::StripeSubscriptionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_stripe_subscription {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_stripe_subscription!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct StripeSubscriptionClient {
    create_checkout_session: NativeRequestHandle<StripeSubscriptionCreateCheckoutSession>,
    create_portal_session: NativeRequestHandle<StripeSubscriptionCreatePortalSession>,
    get_subscription: NativeRequestHandle<StripeSubscriptionGetSubscription>,
}
impl StripeSubscriptionClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn create_checkout_session(&self, request: CreateCheckoutSessionRequest) -> Result<CreateCheckoutSessionResponse, StripeSubscriptionCreateCheckoutSessionInvocationError> {
        self.create_checkout_session.invoke(CREATE_CHECKOUT_SESSION_OPERATION, request).await
            .map_err(StripeSubscriptionCreateCheckoutSessionInvocationError::Runtime)?
            .map_err(StripeSubscriptionCreateCheckoutSessionInvocationError::Domain)
    }

    pub async fn create_checkout_session_with_context(&self, context: InvocationContext, request: CreateCheckoutSessionRequest) -> Result<CreateCheckoutSessionResponse, StripeSubscriptionCreateCheckoutSessionInvocationError> {
        self.create_checkout_session.invoke_with_context(CREATE_CHECKOUT_SESSION_OPERATION, context, request).await
            .map_err(StripeSubscriptionCreateCheckoutSessionInvocationError::Runtime)?
            .map_err(StripeSubscriptionCreateCheckoutSessionInvocationError::Domain)
    }

    pub async fn create_portal_session(&self, request: CreatePortalSessionRequest) -> Result<CreatePortalSessionResponse, StripeSubscriptionCreatePortalSessionInvocationError> {
        self.create_portal_session.invoke(CREATE_PORTAL_SESSION_OPERATION, request).await
            .map_err(StripeSubscriptionCreatePortalSessionInvocationError::Runtime)?
            .map_err(StripeSubscriptionCreatePortalSessionInvocationError::Domain)
    }

    pub async fn create_portal_session_with_context(&self, context: InvocationContext, request: CreatePortalSessionRequest) -> Result<CreatePortalSessionResponse, StripeSubscriptionCreatePortalSessionInvocationError> {
        self.create_portal_session.invoke_with_context(CREATE_PORTAL_SESSION_OPERATION, context, request).await
            .map_err(StripeSubscriptionCreatePortalSessionInvocationError::Runtime)?
            .map_err(StripeSubscriptionCreatePortalSessionInvocationError::Domain)
    }

    pub async fn get_subscription(&self, request: GetSubscriptionRequest) -> Result<GetSubscriptionResponse, StripeSubscriptionGetSubscriptionInvocationError> {
        self.get_subscription.invoke(GET_SUBSCRIPTION_OPERATION, request).await
            .map_err(StripeSubscriptionGetSubscriptionInvocationError::Runtime)?
            .map_err(StripeSubscriptionGetSubscriptionInvocationError::Domain)
    }

    pub async fn get_subscription_with_context(&self, context: InvocationContext, request: GetSubscriptionRequest) -> Result<GetSubscriptionResponse, StripeSubscriptionGetSubscriptionInvocationError> {
        self.get_subscription.invoke_with_context(GET_SUBSCRIPTION_OPERATION, context, request).await
            .map_err(StripeSubscriptionGetSubscriptionInvocationError::Runtime)?
            .map_err(StripeSubscriptionGetSubscriptionInvocationError::Domain)
    }
}

impl CapabilityClient for StripeSubscriptionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            create_checkout_session: dependencies.one::<StripeSubscriptionCreateCheckoutSession>()?,
            create_portal_session: dependencies.one::<StripeSubscriptionCreatePortalSession>()?,
            get_subscription: dependencies.one::<StripeSubscriptionGetSubscription>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for StripeSubscriptionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    create_checkout_session: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionCreateCheckoutSession>()?,
                    create_portal_session: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionCreatePortalSession>()?,
                    get_subscription: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<StripeSubscriptionGetSubscription>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionCreateCheckoutSessionInvocationError {
    Domain(CreateCheckoutSessionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionCreatePortalSessionInvocationError {
    Domain(CreatePortalSessionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum StripeSubscriptionGetSubscriptionInvocationError {
    Domain(GetSubscriptionError),
    Runtime(RuntimeFailure),
}
